# Generated by Django 2.2 on 2019-01-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=0, upload_to='thumbnails'),
        ),
    ]
