# Generated by Django 2.2 on 2019-02-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shorttext',
            field=models.CharField(default='shorttext', max_length=144),
        ),
    ]
